### ISSUE TITLE
Extension error since last update

### ISSUE THREAD

**Issue by mcmxcdev** [esenliyim/sp-tray#12]
I just wanted to update the extension through the GNOME extension website, but it resulted in an error. 
The update yesterday worked without a problem, but the one today broke. Attempting to reinstall also results in an error.

I am running Ubuntu 21.10 with GNOME 40.4.0.

**Comment by esenliyim** [comment]
It's working just fine on my Ubuntu 21.10-Gnome 40 test VM, so you're gonna have to help me help you here. What's the error exactly? May sound obvious, but have you tried logging out and back into your gnome session? It helps sometimes.

**Comment by hiveliberty** [comment]
Same issue for me on Debian 11 (Gnome 3.38)

From logs:
```
Nov 19 15:51:39 someother gnome-shell[5443]: JS ERROR: Extension sp-tray@sp-tray.esenliyim.github.com: Error: A different version was loaded previously. You need to log out for changes to take effect.#012loadExt
ension@resource:///org/gnome/shell/ui/extensionSystem.js:342:52#012callback@resource:///org/gnome/shell/ui/extensionDownloader.js:222:39#012gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloade
r.js:106:13
```

**Comment by esenliyim** [comment]
Yeah I think I know what's happening. I think I'm not handling the disabling of the extension properly, which can cause problems when trying to update it without logging out and back in. I've had it happen to me with some other extensions before.

I'll look into it, but in the meantime, please check and see if uninstalling the extension, restarting gnome-shell and then reinstalling it does the trick.

**Comment by hiveliberty** [comment]
I checked both yesterday.
hm.. logout and login again fix this issue

**Comment by mhatvan** [comment]
Reinstalling extension didn't work for me, but relogging into Ubuntu fixed the issue for me now!
