### ISSUE TITLE
feature request: Integration with ncspot

### ISSUE THREAD

**Issue by thyttan** [esenliyim/sp-tray#14]
I'm running ncspot, a spotify client running inside a terminal window, since it's lightweight. It interacts with the overall system as any media player, i.e. I can use my general multimedia shortcuts and inbuilt gnome media controls to play/pause/next/etc. 

When running the official spotify client I like running spotify-tray, but with ncspot it doesn't pick up on playing tracks. 

Feature request: Make spotify-tray pick up on tracks running in ncspot.

github link to ncspot: https://github.com/hrkfdn/ncspot#readme

Great work with the extension, I like it!

**Comment by esenliyim** [comment]
I've never used anything like that, but I'll take a look.

**Comment by maru-sama** [comment]
@thyttan 
That's the same "issue" as with the last spotify update. the trackid is different..

```  
string "mpris:trackid"
                  variant                      object path "/org/ncspot/spotify/track/1pPaeDn9VZ8GIqqqWRCFYh"
               )
```

**Comment by esenliyim** [comment]
After all this time I think I've finally managed to implement proper support for ncspot. It should work fine now.

**Comment by thyttan** [comment]
That's awesome, thanks!
