### ISSUE TITLE
Does not work with Spotify Web app

### ISSUE THREAD

**Issue by Deottive** [esenliyim/sp-tray#15]
I have been trying to get this to work but it does not happen
Using Ubuntu 20.04 with gnome 3.38

Is this a spotify issue ? if yes then I will stop trying 

Do reply

**Comment by esenliyim** [comment]
Sp-tray doesn't and probably won't ever interface with your web browser, so it won't work with the web app. That's not really an issue with anything, it's just something I haven't implemented and truth be told am not interested in implementing.

Sorry to disappoint, but you can stop trying.
