### ISSUE TITLE
Feature: allow disabling automatic suspend during playback

### ISSUE THREAD

**Issue by molevision** [esenliyim/sp-tray#19]
It would be nice to have the option to disable automatic suspend when currently playing music.

**Comment by esenliyim** [comment]
What do you mean by that? You mean preventing the OS from going to sleep? 

I think the solution to it is simply simulating a dummy key press every few seconds, but IMO the whole idea falls a bit outside the "just a simple label" scope this thing's supposed to have.

**Comment by molevision** [comment]
> I think the solution to it is simply simulating a dummy key press every few seconds, but IMO the whole idea falls a bit outside the "just a simple label" scope this thing's supposed to have.

I suppose the problem lies more so with Spotify.
