### ISSUE TITLE
Extension is incompatible with GNOME 42

### ISSUE THREAD

**Issue by maddiemort** [esenliyim/sp-tray#21]
After updating to GNOME 42.0, this extension cannot be enabled in Extensions, and complains "The extension is incompatible with the current GNOME version".

Do you have plans to update this to be compatible with GNOME 42? I would really appreciate it.

**Comment by esenliyim** [comment]
Yeah, soon. Once I have the time to install 42 on my machine so I can test it to make sure the update hasn't broken anything.

In the meantime, you could try adding "42" into the `shell-version` array in the file `metadata.json` in the extension's base directory. I don't guarantee anything, but have a strong suspicion it'll work just fine.

**Comment by nerosnm** [comment]
Thanks, that seems to be working for now.
