### ISSUE TITLE
Feature request : display format when paused

### ISSUE THREAD

**Issue by whiterqbbit** [esenliyim/sp-tray#25]
Hello,
Could you make an option to have the same format when paused as when playing ?

Thanks a bunch !

**Comment by esenliyim** [comment]
I'm not sure I understand what you mean by that. You mean the track information stays up even when playback is paused?

**Comment by whiterqbbit** [comment]
Exactly.

**Comment by esenliyim** [comment]
Yeah that's not a bad suggestion. I can do it next time I sit down to work on this project.

**Comment by whiterqbbit** [comment]
Thanks!

**Comment by esenliyim** [comment]
I just realized, out of the blue, while showering, that I forgot to update this issue. 

This has been implemented now. As long as the widget is not hidden when playback is paused, you can make it display the metadata of the last seen track by adding the `{metadata}` tag to the text that's displayed when playback is paused. It's in the settings.

I haven't uploaded the latest version onto the website yet, though. If you want that feature, you gotta install the extension manually.
