### ISSUE TITLE
[Feature Request] Text in paused field is not able to show {album} | {track}

### ISSUE THREAD

**Issue by peterge1998** [esenliyim/sp-tray#30]
Hey, I love your extension and its customizeability.
One thing I am missing is to show the {album} | {track} even if playback is stopped.

A toggle to enable showing during stopped could solve this too.

Otherwise, if i paste in {artist} | {album} | {track}, only {art is shown during stopped playback:
![image](https://user-images.githubusercontent.com/47355238/172404031-e71ab7f2-35f3-4af8-98a0-eea67aae8880.png)

**Comment by esenliyim** [comment]
Is #25 what you mean?

**Comment by peterge1998** [comment]
Yes, thats basically the same. However, i describe how this can be controlled by 2 different ways, but feel free to close this if you think my issue is unecessary.

**Comment by esenliyim** [comment]
So I understand you want to have a separate metadata display format for the paused text, is that correct?

**Comment by peterge1998** [comment]
Hi @esenliyim, thanks for looking for this.
These are the 2 posibilities i could imagine to solve this:
1.) Allow more than 4 character in "Paused" field and make {artist} | {album} | {track} work when paused, so th track info shows the whole time regarrless playback is stopped
2.) Add a toggle button, to show the paused text if paused or the opposite (depending on what you want to show by default). Then the logic behind this toggle button that it does not show "Paused" text, or the opposite.

Is my description understandable? Feel free to ask if not

**Comment by peterge1998** [comment]
Oh, great, that seems to do excatly what i want. However, i can just insert `{met` into the "Paused" field, I guess this is because of an old version on extensions.gnome.org, which i am using. Do you have any plans to update it on extensions.gnome.org?

THANKS!

**Comment by esenliyim** [comment]
Yes, that's exactly why you can only type in 4 characters. That's the limit on the current version on extensions.gnome.org, the newer versions have a much higher character limit.

I'll be uploading the most recent version once I've fixed this one problem I've been working on. In the meantime you can manually install it by cloning this repo and running the install script.
