### ISSUE TITLE
Error since last update.

### ISSUE THREAD

**Issue by leTel** [esenliyim/sp-tray#33]
Hi,
Thank you for this great extension.

Unfortunately, it looks like it's not working anymore since the last update.
I'm on Ubuntu 22.04 Gnome version 42.2

Let me know how I can provide you more information.

Best regards.

**Comment by esenliyim** [comment]
I'm on Gnome 42.3 and it's working just fine, so I will need more information.

What's your Spotify version and which package manager did you get it from? Also what kind of "not working" are we talking about? Bad display? No display at all? Something else?

**Comment by esenliyim** [comment]
Actually I just noticed a stupid mistake in the current version. Pushed a quick fix for it, maybe that was it? You can check it out by cloning the repo and manually installing it as described in the readme.

**Comment by leTel** [comment]
It's working again ! Thank you very much !
Have a nice day.
