### ISSUE TITLE
Panel button somehow claims more space than it needs (in static display mode)

### ISSUE THREAD

**Issue by HeroBrine1st** [esenliyim/sp-tray#36]
Hello. 

I hovered cursor and took this screenshot:
![image](https://user-images.githubusercontent.com/22197536/199841624-794f7e39-c808-49b2-b45f-5b175790d1fe.png)
You can see the panel button is bigger than text itself and it exceeds available space, so other panels are shorter than they should be (see four numbers on other screenshorts - they usually have percent and temperature signs).
Settings used: 
![image](https://user-images.githubusercontent.com/22197536/199842022-402dfc85-cc42-46f3-a57a-97d1a0834e98.png)
These settings are that small simply for screenshots, of course. I should say that it does not try to claim all available space (I mean, not always at least) - for example, when I open non-maximized window, "close" and "minimize" buttons are hidden (they are from [Unite](https://github.com/hardpixel/unite-shell) extension btw), so it looks like this:
![image](https://user-images.githubusercontent.com/22197536/199842321-cf355aa9-8006-41b4-8214-f037379b1a51.png)

---

Also, this problem does not appear in marquee mode:
![image](https://user-images.githubusercontent.com/22197536/199842711-aff10603-518e-4b50-a464-c518f1fc1817.png)
![image](https://user-images.githubusercontent.com/22197536/199842728-e1198561-d926-4711-ab81-bcd7597742c0.png)
Even if I try to set absurdly high length limit, it does "smart limit" thing:
![image](https://user-images.githubusercontent.com/22197536/199843386-1e390424-5fd2-486e-9058-24ab84496d3d.png)
![image](https://user-images.githubusercontent.com/22197536/199843401-735430d8-a581-41a2-8c91-c202b5c0b7cc.png)
(Btw, high limit disables the marquee, so you can set it to claim all available space as needed, but without the problem above)

System information:
- Arch Linux (updated like 3-4 days ago, but I don't think it can cause this problem)
- Spotify installed as [a system package](https://aur.archlinux.org/packages/spotify)
- Extension version: 18 (GNOME updated it recently by itself)
- Extension installed [from extensions.grome.org](https://extensions.gnome.org/extension/4472/spotify-tray/)

**Comment by esenliyim** [comment]
I'm like 90% sure what's causing this. I'll get on it ASAP.

**Comment by esenliyim** [comment]
Yeah I was immediately able to recreate it myself. Pushed a fix to the dev branch just now (literally one single line of code), which I hope is the last time I'm fixing this stupid bug. I've fixed and reintroduced it a few times already.

**Comment by HeroBrine1st** [comment]
I ran ./install.sh on dev branch, but don't want to test today (I mean, I'll and start my PC tomorrow and, if would not forget, check it. It's night in my location, so I should sleep already xD)
Did a dirty install tho - didn't delete old version, but I think and hope it's okay.

**Comment by HeroBrine1st** [comment]
Working great! Thank you!
![image](https://user-images.githubusercontent.com/22197536/200016347-405d83df-af09-475f-aeaa-bbb0450f94dd.png)

P.s. I'm not closing as it is a dev version fix
