### ISSUE TITLE
Unnecessary padding with metadata enabled when empty string

### ISSUE THREAD

**Issue by thaumictom** [esenliyim/sp-tray#38]
When I remove the default string of the paused state so that it is empty, and keep "Show metadata when paused?" enabled, there will be padding left of the metadata. It broke with a recent update.

Unpaused: 
![image](https://user-images.githubusercontent.com/15818698/226176466-9ce115d3-c8d9-4061-9171-4bc500caf858.png)
Paused: 
![image](https://user-images.githubusercontent.com/15818698/226176474-34c62a45-8574-4ece-8cbe-6e37910471ac.png)

**Comment by esenliyim** [comment]
Oh I see the problem. There's no padding, that's just the (empty) container that used to display the paused icon, which is a separate thing from the container that displays the metadata string.

I'll deal with it.

**Comment by esenliyim** [comment]
Done. Pushed to Github but I won't be immediately updating the live version.
