### ISSUE TITLE
Feature request: Select positioning, similar to spotify controller

### ISSUE THREAD

**Issue by ImOnALampshade** [esenliyim/sp-tray#4]
I'd prefer to have the positioning of the tray on the left side of my menu bar. This is possible with [Spotify Controller](https://extensions.gnome.org/extension/4013/spotify-controller/), which I use alongside this, but I can't get them both positioned on the left side.

**Comment by esenliyim** [comment]
I'll look into it

**Comment by esenliyim** [comment]
It has successfully been looked into.
