### ISSUE TITLE
Missing gschemas.compiled

### ISSUE THREAD

**Issue by DeJayDev** [esenliyim/sp-tray#44]
Hi there,

Thank you for upgrading to GNOME 45!

However, `spotify-tray` version 23 fails to start (at least on my system) with the following error message:
```
GLib.FileError: Failed to open file “/home/dj/.local/share/gnome-shell/extensions/sp-tray@sp-tray.esenliyim.github.com/schemas/gschemas.compiled”: open() failed: No such file or directory
```

Which would be correct, the `schemas` dir was empty locally. It appears that `gschemas.compiled` and `org.gnome.shell.extensions.sp-tray.gschema.xml` weren't included in the update. 

Locally, this is fixable either:
* Downloading of those files from the repo and dropping them in `~/.local/share/gnome-shell/extensions/sp-tray@sp-tray.esenliyim.github.com/schemas` 
or
* Downloading `org.gnome.shell.extensions.sp-tray.gschema.xml` to the `schemas` folder and running `glib-compile-schemas .`

Here's a quick fix for others who may be having this issue:
```bash
wget -P ~/.local/share/gnome-shell/extensions/sp-tray@sp-tray.esenliyim.github.com/schemas https://github.com/esenliyim/sp-tray/blob/master/schemas/org.gnome.shell.extensions.sp-tray.gschema.xml
glib-compile-schemas ~/.local/share/gnome-shell/extensions/sp-tray@sp-tray.esenliyim.github.com/schemas
```

**Comment by esenliyim** [comment]
Yeah that was a dumb mistake from me. The file is actually there in the package that was submitted, but it somehow gets wiped if you don't include the source xml with it, which I apparently did not, for some reason.

Anyway, version 24 has been uploaded with the correct files. It should go online shortly.
