### ISSUE TITLE
Podcast artist missing

### ISSUE THREAD

**Issue by ncka1** [esenliyim/sp-tray#7]
Artist field appears to be missing when playing a podcast.

If this isn't possible to fix, could also display track field only (with no | or spaces) when artist field is missing

**Comment by esenliyim** [comment]
Sorry for the late reply. 

I'll look into it soon. I just never use Spotify for podcasts so it never even occured to me to test for this stuff hehe

**Comment by esenliyim** [comment]
I have now separated the podcast display format from normal track display format. Check it out, let me know what you think.

**Comment by ncka1** [comment]
Very nice! Is working perfectly. This is an elegant solution.
