### ISSUE TITLE
Max track/album/artist character length

### ISSUE THREAD

**Issue by ncka1** [esenliyim/sp-tray#8]
Titles can get quite long. Would it be possible to set max length for track and artist fields?

**Comment by esenliyim** [comment]
You can now set max lengths for all 3 fields. Minimum length is 5, maximum is 200. I picked 35 as a default, thought it looked reasonable.

**Comment by ncka1** [comment]
Works great! thanks for looking at this.

**Comment by ncka1** [comment]
I modified my panelButton.js so that ellipses are added when the fields are truncated

**Comment by esenliyim** [comment]
Ye that makes a lot of sense, actually. I could merge that if you made a PR. Or I could just do it myself.

**Comment by ncka1** [comment]
I'm not a programmer, so I may not have done it the best way:

```
let title = metadata['xesam:title'].get_string()[0];
if (title.length > maxTitleLength)
    title = title.slice(0,maxTitleLength) + "...";
                    
let album = metadata['xesam:album'].get_string()[0]
if (album.length > maxAlbumLength)
    album = album.slice(0,maxAlbumLength) + "...";
                    	
let artist = metadata['xesam:albumArtist'].get_strv()[0]
if (artist.length > maxArtistLength)
    artist = artist.slice(0,maxArtistLength) + "...";
```

If you would like me to do a PR, I'll figure out how to do that.

**Comment by esenliyim** [comment]
The code looks functionally fine, I'd accept it.

But I'd appreciate it if you could enclose the bodies of the if statements with curly brackets. I don't like having loops and if statements without brackets in my code, even for single-line stuff.

**Comment by ncka1** [comment]
Done. Thanks again!
